### PR TITLE
doc: fix broken link to etcd documentation

### LINKED ISSUE #1018: Page not found in README.md
The [instruction ](https://github.com/etcd-io/etcd/blob/main/Documentation/dl_build.md) in [jetcd-ctl/README.md](https://github.com/etcd-io/jetcd/blob/master/jetcd-ctl/README.MD) is missing.
Plz update doc. Thanks a lot.

### PR DESCRIPTION
**Pull request by sudoHackIn**
Hello i would like to contribute by fixing this issue - https://github.com/etcd-io/jetcd/issues/1018

For me - https://github.com/etcd-io/etcd/releases#:~:text=Compare-,v3.5.1,-Latest provides best instruction to etcd cluster creation (best working docker example)
But https://etcd.io/docs/v3.5/install/ this works better as an instruction

Fixes #1018

### CODE REVIEW

**Comment by lburgazzoli** [comment]
> Hello i would like to contribute by fixing this issue - #1018
> 
> For me - [etcd-io/etcd/releases#:~:text=Compare-,v3.5.1,-Latest](https://github.com/etcd-io/etcd/releases#:~:text=Compare-,v3.5.1,-Latest) provides best instruction to etcd cluster creation (best working docker example) But [etcd.io/docs/v3.5/install](https://etcd.io/docs/v3.5/install/) this works better as an instruction
> 
> Fixes #1018

I agree that the first link is much better however that would put some additional work as we may need to update the doc accogin to the etcd releases cadence.

What about just pointing to https://github.com/etcd-io/etcd/blob/main/README.md ?

**Comment by sudoHackIn** [comment]
After spending some unpleasant time, finding how to run etcd cluster, i insist to use that link :) 
As i understand, this link will always reference latest version and we won't update every release
https://github.com/etcd-io/etcd/releases/latest 

Aditionally we can reference main etcd readme as main document url. How do you think?


> > Hello i would like to contribute by fixing this issue - #1018
> > For me - [etcd-io/etcd/releases#:~:text=Compare-,v3.5.1,-Latest](https://github.com/etcd-io/etcd/releases#:~:text=Compare-,v3.5.1,-Latest) provides best instruction to etcd cluster creation (best working docker example) But [etcd.io/docs/v3.5/install](https://etcd.io/docs/v3.5/install/) this works better as an instruction
> > Fixes #1018
> 
> I agree that the first link is much better however that would put some additional work as we may need to update the doc accogin to the etcd releases cadence.
> 
> What about just pointing to https://github.com/etcd-io/etcd/blob/main/README.md ?

After spending some unpleasant time, finding how to run etcd cluster, i insist to use that link :) 
As i understand, this link will always reference latest version and we won't update every release
https://github.com/etcd-io/etcd/releases/latest 

Aditionally we can reference main etcd readme as main document url. How do you think?

**Comment by lburgazzoli** [comment]
which link exactly, I'm confused

**Comment by sudoHackIn** [comment]
> which link exactly you want to use, I'm confused

This one, that always pointing to latest and won't need additional work to update

https://github.com/etcd-io/etcd/releases/latest

**Comment by lburgazzoli** [comment]
that's fine, can you update the pr ?

**Comment by sudoHackIn** [comment]
> that's fine, can you update the pr ?

Sure

**Comment by sudoHackIn** [comment]
Can i somehow contribute to project more? Can't find any actual issues

**Comment by sudoHackIn** [comment]
Can i somehow contribute to project more? Can't find any actual issues

**Comment by lburgazzoli** [comment]
> Can i somehow contribute to project more? Can't find any actual issues

of course you can.

you can pick any issue or contribute docs, tests

**Pull request merged**
