### PR TITLE
build(deps): bump grpc from 1.57.2 to 1.58.0

### PR DESCRIPTION
**Pull request by lburgazzoli**
- build(deps): bump grpc from 1.57.2 to 1.58.0
- chore: remove deprecated method
- chore: re-format enum definitions

### CODE REVIEW

**Comment by liangyuanpeng** [comment]
While I'd be wary of upgrading grpc dependencies quickly, given the fact that you've already done it I say OK.

There are two commit have not DCO.  😅

**Comment by johnshajiang** [comment]
> There are two commit have not DCO.

As I suggested in PR #1219, it would be better to squash the multiple commits when merge a PR.
Then, we can make the repository more clean. Especially, that could double-check if the single commit meets the rules.

**Comment by liangyuanpeng** [comment]
Good suggesstion, and this is also common practice for CNCF projects, Unless there is a clear purpose, only one commit is needed when merging.

@lburgazzoli  WDYT?   😄

**Comment by lburgazzoli** [comment]
> > There are two commit have not DCO.
> 
> As I suggested in PR #1219, it would be better to squash the multiple commits when merge a PR. Then, we can make the repository more clean. Especially, that could double-check if the single commit meets the rules.

The commits are related to different things, not necessarily the upgrade of grpc itself that is why they are not squashed into one.

**Comment by lburgazzoli** [comment]
> While I'd be wary of upgrading grpc dependencies quickly, given the fact that you've already done it I say OK.
> 

This grpc version introduced some changes that required some manual intervention so I rather try to do it when I have time which at this stage happened to be now rather than accumulating changes

**Comment by liangyuanpeng** [comment]
> The commits are related to different things, not necessarily the upgrade of grpc itself that is why they are not squashed into one.

Absolutely, i can see there are different things and this PR is treated correctly.

>  I rather try to do it when I have time which at this stage happened to be now rather than accumulating changes

Make sense for today. Jetcd have not  more active dever.

**Comment by lburgazzoli** [comment]
@liangyuanpeng if you step in and help the project, then I would definitively appreciate it and we can plan things a little bit  better rather than "I do stuffs when I can" :)

**Pull request merged**
