### PR TITLE
modify grpc-netty dependency as grpc-netty-shaded

### PR DESCRIPTION
**Pull request by riverlee2014**
change the pom.xml dependency of 'jetc-core' module and the java import package, make it dependent on grpc-netty-shaded to reduce netty library exposure.

### CODE REVIEW

**Comment by lburgazzoli** [comment]
Looks like the PR is not good

**Comment by lburgazzoli** [comment]
@riverlee2014 can we close this as we have now solved the shading issue with jetcd-all ?

**Comment by riverlee2014** [comment]
> @riverlee2014 can we close this as we have now solved the shading issue with jetcd-all ?

Yes, thank you. When will the new version be released?

**Comment by lburgazzoli** [comment]
This week, I hope :)

**Pull request closed without merging**
