### PR TITLE
Change prefix param type to boolean.

### PR DESCRIPTION
**Pull request by horizonzy**
for-#934.
When user didn't set withRange and prefix is true, use the key which from invocation param to build rangeEnd

### CODE REVIEW

**Comment by horizonzy** [comment]
@lburgazzoli can you help to trigger it.

**Comment by horizonzy** [comment]
@lburgazzoli Hi, do me a favor to trigger it, thanks.

**Comment by lburgazzoli** [comment]
@horizonzy anything more you want to include ?

**Comment by horizonzy** [comment]
That's enough.

**Pull request merged**
